language: ruby
rvm:
  - 2.1.3
gemfile: docs/manual/Gemfile
script:
  - cd docs/manual
  - bundle exec middleman build



deploy:
  provider: s3
  access_key_id:
    secure: "duN9qO+AlXMDKsVgChAplEVg3CRLevasNyHcbxjFesNJYRybOQqKIG1Ztdm14qHGn+l8vDxScDTto9qLjgPQhTKxcWZM/JIppDa2K9OJLUeacX5oDyfPqpXJbU4ucRG9Bj4p6mpeVUXPR546jqsXMqj1A8evUDgj2L50ztPN3IQ="
  secret_access_key:
    secure: "UvuGdt3L7PkZehx0YSsXvDwHDFIvC5NkwjfBo+tLD/3/qYgFUZIbmtSbTCMqgG/P0H/xu7KGIZ8BRmcL71dVE9Uj+0kWjBMBak0XQFegEhZrehmLTJpSO+nm5Au1PthWaoA1YePVZmeXKagoDuWboMTXZ0ZZqFGuVFWQYU9MuSU="
  bucket: "docs.prediction.io"
  region: "us-east-1"
  skip_cleanup: true
  endpoint: "docs.prediction.io.s3-website-us-east-1.amazonaws.com"
  local-dir: build
  detect_encoding: true
  on: develop


branches:
  only:
    - develop
    - master
    - livedoc