env:
  global:
    - secure: "UKsdCiTc9APZ5gjE6nidw+xJKOv0yfGDUtNEp+Zldo20QPA0yx/ESjtb4UOhqw7iqraLsIKU315xWhb7PEFiVgxtMUhDzwWY+dN6klMDhbTovAb0GQH8a07yCQ2cNX2/xm75RmBAZb5lmdR45t/QXdqwzjQ+i1cbRsGOYIHNkLk="
    - secure: "Xz1UJTWIRoTclqewsTv5jInihZowciFd5l/0wi2JpUQO2pVqcKKgMRuedzUCtyqe5xroDIhTs9bwwwRtYzcjFTS9gqgVRX0Ak0pEUrP0X0torTXaEzbuDKq5xf8tXtd2MCChDGi67i/6uy+2j9uoiN/DuhTxoCfUAjgGWWpYeso="
    - CF_DISTRIBUTION_ID=E2KH6C4FF8P5BK
language: ruby
rvm:
  - 2.1.3
gemfile: docs/manual/Gemfile

branches:
  only:
    - develop
    - master
    - livedoc

script:
  - cd docs/manual
  - bundle exec middleman build
  - bundle exec middleman server &
deploy:
  provider: s3
  access_key_id:
    secure: "duN9qO+AlXMDKsVgChAplEVg3CRLevasNyHcbxjFesNJYRybOQqKIG1Ztdm14qHGn+l8vDxScDTto9qLjgPQhTKxcWZM/JIppDa2K9OJLUeacX5oDyfPqpXJbU4ucRG9Bj4p6mpeVUXPR546jqsXMqj1A8evUDgj2L50ztPN3IQ="
  secret_access_key:
    secure: "hcKVgp3EN3Sdsxm0kqllX8sj368kHsodhJ7DRsw7Jtm+eEWD744mUyoO+4CNxT8j3lbB0sbuU/+mZDmkOfSO4m3m6JB46WAmBDXwVSi0tJ1Uroh44mjK1u/nXDuSoFo3sNJPK7+EX4aUXAjxlOG+yfGN0VICHym5HJOaJ/B23cI="
  bucket: docs.prediction.io
  region: us-east-1
  skip_cleanup: true
  endpoint: docs.prediction.io.s3-website-us-east-1.amazonaws.com
  local-dir: build
  detect_encoding: true
  on: develop

after_success:
  - bundle exec middleman invalidate
